### ISSUE TITLE
[Help]: NetCDF: Can't open HDF5 attribute

### ISSUE THREAD

**Issue by fpucci** [mobigroup/gmtsar#107]
Hi @AlexeyPechnikov 
I am using th notebook Yamchi Dam but with different S1 images (AOI and dates). During execution of step " Multi-looked Resolution for SBAS" I get multipl times the following exception:
```
Exception ignored in: <function CachingFileManager.__del__ at 0x7f08b2953d80>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 250, in __del__
    self.close(needs_lock=False)
  File "/opt/conda/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 234, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2627, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2590, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2034, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
```
and, at the end:
```

HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 1327 in H5Aiterate2(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 2:
  #000: H5A.c line 1327 in H5Aiterate2(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
2024-02-21 20:42:11,026 - distributed.worker - WARNING - Compute Failed
Key:       open_dataset-fb68442b-b147-41f0-a177-f87fb2d3ed7e
Function:  execute_task
args:      ((<function apply at 0x7fad87ff7560>, <function open_dataset at 0x7fad6a4ffba0>, ['./test/raw_altolia_asc/S1_20201018_ALL_F2.grd'], (<class 'dict'>, [['engine', 'netcdf4'], ['chunks', 2048]])))
kwargs:    {}
Exception: 'AttributeError("NetCDF: Can\'t open HDF5 attribute")'

2024-02-21 20:42:11,026 - distributed.worker - WARNING - Compute Failed
Key:       open_dataset-bb70dfda-72f6-4f12-84a5-4318fc2e0bc8
Function:  execute_task
args:      ((<function apply at 0x7fad87ff7560>, <function open_dataset at 0x7fad6a4ffba0>, ['./test/raw_altolia_asc/S1_20201217_ALL_F2.grd'], (<class 'dict'>, [['engine', 'netcdf4'], ['chunks', 2048]])))
kwargs:    {}
Exception: 'RuntimeError("NetCDF: Can\'t open HDF5 attribute")'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[35], line 1
----> 1 sbas.compute_interferogram_multilook(baseline_pairs, 'intf_mlook', wavelength=100, weight=sbas.psfunction())

File /opt/conda/lib/python3.11/site-packages/pygmtsar/Stack_phasediff.py:107, in Stack_phasediff.compute_interferogram_multilook(self, pairs, name, resolution, weight, phase, wavelength, psize, coarsen, queue, timeout, debug)
    105 def compute_interferogram_multilook(self, pairs, name, resolution=None, weight=None, phase=None,
    106                                     wavelength=None, psize=None, coarsen=(1,4), queue=16, timeout=None, debug=False):
--> 107     self.compute_interferogram(pairs, name, resolution=resolution, weight=weight, phase=phase, wavelength=wavelength,
    108                                psize=psize, coarsen=coarsen, queue=queue, timeout=timeout, debug=debug)

File /opt/conda/lib/python3.11/site-packages/pygmtsar/Stack_phasediff.py:52, in Stack_phasediff.compute_interferogram(self, pairs, name, resolution, weight, phase, wavelength, psize, coarsen, queue, timeout, debug)
     50 chunk, dates = self.get_pairs(chunk, dates=True)
     51 # load Sentinel-1 data
---> 52 data = self.open_data(dates, debug=debug)
     53 intensity = np.square(np.abs(data))
     54 # Gaussian filtering 200m cut-off wavelength with optional range multilooking on Sentinel-1 amplitudes

File /opt/conda/lib/python3.11/site-packages/pygmtsar/IO.py:267, in IO.open_data(self, dates, scale, debug)
    265 filenames = [self.PRM(date).filename[:-4] + '.grd' for date in dates]
    266 #print ('filenames', filenames)
--> 267 ds = xr.open_mfdataset(
    268     filenames,
    269     engine=self.netcdf_engine,
    270     chunks=self.chunksize,
    271     parallel=True,
    272     concat_dim='date',
    273     combine='nested'
    274 ).assign(date=pd.to_datetime(dates)).rename({'a': 'y', 'r': 'x'})
    275 if scale is None:
    276     # there is no complex int16 datatype, so return two variables for real and imag parts
    277     return ds

File /opt/conda/lib/python3.11/site-packages/xarray/backends/api.py:1033, in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
   1028     datasets = [preprocess(ds) for ds in datasets]
   1030 if parallel:
   1031     # calling compute here will return the datasets/file_objs lists,
   1032     # the underlying datasets will still be stored as dask arrays
-> 1033     datasets, closers = dask.compute(datasets, closers)
   1035 # Combine all datasets, closing them in case of a ValueError
   1036 try:

File /opt/conda/lib/python3.11/site-packages/dask/base.py:663, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    660     postcomputes.append(x.__dask_postcompute__())
    662 with shorten_traceback():
--> 663     results = schedule(dsk, keys, **kwargs)
    665 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File /opt/conda/lib/python3.11/site-packages/xarray/backends/api.py:572, in open_dataset()
    560 decoders = _resolve_decoders_kwargs(
    561     decode_cf,
    562     open_backend_dataset_parameters=backend.open_dataset_parameters,
   (...)
    568     decode_coords=decode_coords,
    569 )
    571 overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 572 backend_ds = backend.open_dataset(
    573     filename_or_obj,
    574     drop_variables=drop_variables,
    575     **decoders,
    576     **kwargs,
    577 )
    578 ds = _dataset_from_backend_dataset(
    579     backend_ds,
    580     filename_or_obj,
   (...)
    590     **kwargs,
    591 )
    592 return ds

File /opt/conda/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:658, in open_dataset()
    656 store_entrypoint = StoreBackendEntrypoint()
    657 with close_on_error(store):
--> 658     ds = store_entrypoint.open_dataset(
    659         store,
    660         mask_and_scale=mask_and_scale,
    661         decode_times=decode_times,
    662         concat_characters=concat_characters,
    663         decode_coords=decode_coords,
    664         drop_variables=drop_variables,
    665         use_cftime=use_cftime,
    666         decode_timedelta=decode_timedelta,
    667     )
    668 return ds

File /opt/conda/lib/python3.11/site-packages/xarray/backends/store.py:43, in open_dataset()
     29 def open_dataset(  # type: ignore[override]  # allow LSP violation, not supporting **kwargs
     30     self,
     31     filename_or_obj: str | os.PathLike[Any] | BufferedIOBase | AbstractDataStore,
   (...)
     39     decode_timedelta=None,
     40 ) -> Dataset:
     41     assert isinstance(filename_or_obj, AbstractDataStore)
---> 43     vars, attrs = filename_or_obj.load()
     44     encoding = filename_or_obj.get_encoding()
     46     vars, attrs, coord_names = conventions.decode_cf_variables(
     47         vars,
     48         attrs,
   (...)
     55         decode_timedelta=decode_timedelta,
     56     )

File /opt/conda/lib/python3.11/site-packages/xarray/backends/common.py:212, in load()
    189 """
    190 This loads the variables and attributes simultaneously.
    191 A centralized loading function makes it easier to create
   (...)
    207 are requested, so care should be taken to make sure its fast.
    208 """
    209 variables = FrozenDict(
    210     (_decode_variable_name(k), v) for k, v in self.get_variables().items()
    211 )
--> 212 attributes = FrozenDict(self.get_attrs())
    213 return variables, attributes

File /opt/conda/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:465, in get_attrs()
    464 def get_attrs(self):
--> 465     return FrozenDict((k, self.ds.getncattr(k)) for k in self.ds.ncattrs())

File src/netCDF4/_netCDF4.pyx:3035, in netCDF4._netCDF4.Dataset.ncattrs()

File src/netCDF4/_netCDF4.pyx:1521, in netCDF4._netCDF4._get_att_names()

File src/netCDF4/_netCDF4.pyx:2034, in netCDF4._netCDF4._ensure_nc_success()

AttributeError: NetCDF: Can't open HDF5 attribute

```

what could be the reason? Thank you in advance for your help.

**Comment by AlexeyPechnikov** [comment]
Please refer to #105 for the solution and kindly provide details about your hardware (Intel/AMD x64, Arm, etc.) and host operating system (Linux, Windows, MacOS) to reproduce the issue on my side.

**Comment by AlexeyPechnikov** [comment]
The recent Docker image uses the same NetCDF backend as on Google Colab, etc. If the problem still occurs, please create a new ticket.
