### ISSUE TITLE
Problem downloading ASF data

### ISSUE THREAD

**Issue by Smitrgeo15** [mobigroup/gmtsar#112]
# Set these variables to None and you will be prompted to enter your username and password below.
asf = ASF(asf_username, asf_password)
# Optimized scene downloading from ASF - only the required subswaths and polarizations.
print(asf.download_scenes(DATADIR, SCENES, SUBSWATH))
# There are two ways to download orbits; you can use any one or both together.
try:
    # RESORB orbit downloading from ASF has recently failed.
    print(asf.download_orbits(DATADIR))
except Exception as e:
    print (e)
    # Download missed orbits in case ASF orbit downloading fails.
    esa = ESA(esa_username, esa_password)
    print (esa.download_orbits(DATADIR))
    using this commands in PyGMTSAR i am unable to download the scenes

ERROR:
ASF Downloading Sentinel-1 SLC:  33%
 8/24 [00:12<03:10, 11.88s/it]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/remotezip.py", line 226, in fetch
    res, range_header = self._request(kwargs)
  File "/usr/local/lib/python3.10/dist-packages/remotezip.py", line 192, in _request
    res.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20170324T011358_20170324T011425_015827_01A12B_940F%20%20%20%20.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py", line 105, in download_scene
    with asf_search.remotezip(url, session) as remotezip:
  File "/usr/local/lib/python3.10/dist-packages/asf_search/download/download.py", line 89, in remotezip
    return RemoteZip(url, session=session)
  File "/usr/local/lib/python3.10/dist-packages/remotezip.py", line 245, in __init__
    super(RemoteZip, self).__init__(rio)
  File "/usr/lib/python3.10/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1332, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python3.10/zipfile.py", line 266, in _EndRecData
    fpin.seek(0, 2)
  File "/usr/local/lib/python3.10/dist-packages/remotezip.py", line 145, in seek
    self.buffer = self._fetch_fun((-size, None), stream=False)
  File "/usr/local/lib/python3.10/dist-packages/remotezip.py", line 230, in fetch
    raise RemoteIOError(str(e))
remotezip.RemoteIOError: 404 Client Error: NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20170324T011358_20170324T011425_015827_01A12B_940F%20%20%20%20.zip
"""

The above exception was the direct cause of the following exception:

RemoteIOError                             Traceback (most recent call last)
[<ipython-input-22-108f5f0ac3c3>](https://localhost:8080/#) in <cell line: 4>()
      2 asf = ASF(asf_username, asf_password)
      3 # Optimized scene downloading from ASF - only the required subswaths and polarizations.
----> 4 print(asf.download_scenes(DATADIR, SCENES, SUBSWATH))
      5 # There are two ways to download orbits; you can use any one or both together.
      6 try:

6 frames
[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _return_or_raise(self)
    752         try:
    753             if self.status == TASK_ERROR:
--> 754                 raise self._result
    755             return self._result
    756         finally:

RemoteIOError: 404 Client Error: NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20170324T011358_20170324T011425_015827_01A12B_940F%20%20%20%20.zip
how to solve this problem

**Comment by AlexeyPechnikov** [comment]
The error message is clear:
```
NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20170324T011358_20170324T011425_015827_01A12B_940F%20%20%20%20.zip
```
The scene cannot be found because its identifier ends with a set of whitespaces ('...940F%20%20%20%20.zip'). You need to fix the scene names.

**Comment by Smitrgeo15** [comment]
![Screenshot 2024-03-16 112814](https://github.com/AlexeyPechnikov/pygmtsar/assets/88897405/bc899bdc-1379-4aed-8c14-ac730dbd8d08)
How to correct the scene ID link ?
I have just copied the scene ID from ASF but i do not how to clear the whitespaces "NOT FOUND for url: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20170324T011358_20170324T011425_015827_01A12B_940F%20%20%20%20.zip"

**Comment by AlexeyPechnikov** [comment]
Check for any invisible whitespace characters (tiling) and remove them.

**Comment by y-okur** [comment]
Hi Alexey,

I have a problem with downloading ASF data.

I am trying to run one of your Google Colab Notebook: https://colab.research.google.com/drive/1TARVTB7z8goZyEVDRWyTAKJpyuqZxzW2?usp=sharing

At cell [16], I am receiving this error:

ASF Downloading Sentinel-1 SLC::  67%
 8/12 [00:18<01:14, 18.61s/it]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygmtsar/ASF.py", line 148, in download_scene
    assert os.path.getsize(fullname + '.tmp') == filesize, \
AssertionError: ERROR: Downloaded incomplete scene content
"""

The above exception was the direct cause of the following exception:

AssertionError                            Traceback (most recent call last)
[<ipython-input-16-c5e32b0ca12b>](https://localhost:8080/#) in <cell line: 4>()
      2 asf = ASF(asf_username, asf_password)
      3 # Optimized scene downloading from ASF - only the required subswaths and polarizations.
----> 4 print(asf.download_scenes(DATADIR, SCENES, SUBSWATH))

6 frames
[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _return_or_raise(self)
    761         try:
    762             if self.status == TASK_ERROR:
--> 763                 raise self._result
    764             return self._result
    765         finally:

AssertionError: ERROR: Downloaded incomplete scene content

I am also receiving the same error when I try download different scenes with SUBSWATH=123 option.

Do you have any idea what might be the problem?

Thanks in advance

**Comment by AlexeyPechnikov** [comment]
The error is pretty clear:
```
ERROR: Downloaded incomplete scene content
```
You suffer from a network error or issue at the ASF datastore. Run the cell again or relaunch the entire notebook to continue the downloading.

**Comment by y-okur** [comment]
> The error is pretty clear:
> 
> ```
> ERROR: Downloaded incomplete scene content
> ```
> 
> You suffer from a network error or issue at the ASF datastore. Run the cell again or relaunch the entire notebook to continue the downloading.

Hi Alexey,

Thank you for the quick response.

I tried downloading one swath at a time using:
```
print(asf.download_scenes(DATADIR, SCENES, 1))
print(asf.download_scenes(DATADIR, SCENES, 2))
print(asf.download_scenes(DATADIR, SCENES, 3))
```
and the problem is resolved now.

**Comment by AlexeyPechnikov** [comment]
Nice. FYI, this is not related to the number of swaths but only a temporary downloading error. PyGMTSAR example notebooks can produce such errors once or even for hours when an unpredictable network connection issue arises or the ASF datastore is in a maintenance state.

**Comment by jie666-6** [comment]
Actually, I got the same issue and solve it in the exactly same way. I am not sure if it is a really network issue or not. Because I can use the asf_search to download data directly, no connection problem exist.

**Comment by AlexeyPechnikov** [comment]
asf_search downloads complete scenes, whereas PyGMTSAR extracts and downloads individual subswaths, significantly reducing network traffic and local disk space usage (since a complete scene includes two polarizations and three subswaths). However, this process requires a stable network connection because accessing remote zip archives is sensitive to disruptions and cannot be resumed in the same manner as downloading a complete file.

**Comment by mhotalebi** [comment]
i wanna run PyGMTSAR SBAS and PSI Analyses code on my local machine and when i download ASF Downloading Sentinel-1 Bursts after finishing download the following error happened. i use path in other drives but it download in download folder. 
PermissionError: [WinError None] The process cannot access the file because it is being used by another process: 'asc2\\S1A_IW_SLC__1SDV_20240803T143446_20240803T143449_055050_06B4F5_EE29.SAFE\\s1a-iw2-slc-vh-20240803t143446-20240803t143449-055050-06b4f5-001.tiff' -> 'asc2\\S1A_IW_SLC__1SDV_20240803T143446_20240803T143449_055050_06B4F5_EE29.SAFE\\measurement\\s1a-iw2-slc-vh-20240803t143446-20240803t143449-055050-06b4f5-001.tiff'
![Capture](https://github.com/user-attachments/assets/7421e338-ec2e-453e-8a74-e78bfeba47dd)

**Comment by AlexeyPechnikov** [comment]
Concurrent file access is the Achilles’ heel of Windows. You should use PyGMTSAR Docker images to perform InSAR processing on Windows.

**Comment by mhotalebi** [comment]
is it possible to download it manually and replace it on workplace folder and run the rest of the code?

**Comment by AlexeyPechnikov** [comment]
I didn’t try to run on Windows natively. It means you need to compile and install GMTSAR binaries and SNAPHU first.

**Comment by Tnecniv-Teikram** [comment]
edit: never mind, I did some more testing and found out that the credentials did work outside the docker container within a new environment and just importing the asf_search api.

I will keep investigating why inside the docker container my credentials strings/variables do not get properly parsed. 

# -------------------- #

You can ignore this error.

# -------------------- #

I keep getting Username or password is incorrect errors when running the asf.download() function from within the pygmtsar docker image. Despite the same credentials working fine outside the docker file in all your colab examples as well as the ASF website.

I have special characters in my username and password. 
I've tried adding them to a .env file and import them in my makefile when running the docker, but no luck. 

I then started debugging inside the docker container. I opened the bash terminal and used python3 to hardcode all the variables, similar to your google colab notebooks, but still get the same error.

In the python interpreter Inside the docker I simply do:

python3

from pygmtsar import ASF

asf_username='my_username'
asf_password='my_password' 


>>> asf = ASF(asf_username, asf_password)
>>> BURSTS = ['S1_277219_IW2_20230828T142458_VV_04F2-BURST']
>>> DATADIR ='/'
>>> asf.download(DATADIR,BURSTS)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.12/site-packages/pygmtsar/ASF.py", line 74, in download
    result = self.download_bursts(basedir, bursts, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pygmtsar/ASF.py", line 619, in download_bursts
    session = self._get_asf_session()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pygmtsar/ASF.py", line 35, in _get_asf_session
    return asf_search.ASFSession().auth_with_creds(self.username, self.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/asf_search/ASFSession.py", line 136, in auth_with_creds
    self._legacy_creds_auth()
  File "/opt/conda/lib/python3.12/site-packages/asf_search/ASFSession.py", line 191, in _legacy_creds_auth
    raise ASFAuthenticationError('Username or password is incorrect')
asf_search.exceptions.ASFAuthenticationError: Username or password is incorrect
>>> 



I then checked the ASF profile applications to see if the proper permissions are granted for API access.

<img width="977" height="772" alt="Image" src="https://github.com/user-attachments/assets/472b5a99-2316-4dff-a33e-72c5a7330af5" />

**Comment by AlexeyPechnikov** [comment]
I’ve checked now and the asf_search lib is outdated in the images. Update it in the Docker container console and it will work again:

sudo /opt/conda/bin/pip3 install -U asf_search
