### ISSUE TITLE
[Help]: Error with compute_reframe(AOI)

### ISSUE THREAD

**Issue by geofysue** [mobigroup/gmtsar#119]
I am running the Lake Sarez Landslides script, but using my own set of images in other area. I am using 287 S1 products. I have created the AOI as:
```
geojson = '''
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [-0.6929, 38.2841] 
  },
  "properties": {}
}
'''
BUFFER = 0.1
AOI = gpd.GeoDataFrame.from_features([json.loads(geojson)])
AOI['geometry'] = AOI.buffer(BUFFER)
```
But there is an error with SAT_llr2rat() function when running compure_reframe(AOI):
```
.
.
.
Tiles Parallel Downloading: 100%|████████████████████████████████| 1/1 [00:02<00:00,  2.78s/it]
NOTE: auto set reference scene 2017-01-06. You can change it like Stack.set_reference("2022-01-20")
Reframing:  18%|████████▏                                     | 51/287 [02:34<11:53,  3.02s/it]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py", line 87, in _reframe_subswath
    tmpazi_a = prm.SAT_llt2rat([geometry.coords[0][0],  geometry.coords[0][1],  0], precise=1, debug=debug)[1]
IndexError: index 1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tidop/Documentos/PYTHON_SCRIPTS/test_pygmtsar03-FIXED.py", line 446, in <module>
    sbas.compute_reframe(AOI)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/pygmtsar/Stack_reframe.py", line 189, in compute_reframe
    records = joblib.Parallel(n_jobs=n_jobs, backend=joblib_backend)(joblib.delayed(self._reframe_subswath)\
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/tidop/anaconda3/envs/pygmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
IndexError: index 1 is out of bounds for axis 0 with size 0
```
Also, I encounter a warning when downloading, that may affect:
```
ASF Downloading POEORB Orbits:  17%|████▌                     | 50/287 [02:16<10:46,  2.73s/it]
('Connection broken: IncompleteRead(4144906 bytes read, 264817 more expected)', IncompleteRead(4144906 bytes read, 264817 more expected))
```
Thanks!

**Comment by AlexeyPechnikov** [comment]
Processing is not possible when orbits or DEM files are incomplete or invalid. You have to re-download your orbits to fix the problem.
