### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Arslaan4341** [mobigroup/gmtsar#13]
I am trying to reframe the images for time series-analysis using SBAS, while defining the pins to 'none' to take in account the full master image, but an error pops up while using sbas.reframe_parallel(dates=None, n_jobs=6).
Software Used- Spyder.
I am using the following code.
from pygmtsar import SBAS
from pygmtsar import PRM
import numpy as np
import xarray as xr
import os
import glob
WORKDIR  = 'D:/output'
DATADIR  = 'D:/insar'
file_path = r'D:/insar'
CORRLIMIT  = 0.10
DEFOMAX  = 0
files = os.listdir(file_path)
print(files)
sbas = SBAS(DATADIR, basedir=WORKDIR)
print (sbas.to_dataframe())
sbas.download_orbits()
print (sbas.to_dataframe())
sbas.set_pins([None,None],[None,None],[None,None])
sbas.reframe_parallel(dates=None, n_jobs=12)
print (sbas.get_pins())
sbas.to_dataframe()

The output shows as-
sbas.reframe_parallel(dates=None, n_jobs=12)
Reframing:   0%|          | 0/6 [00:00<?, ?it/s]
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\joblib\externals\loky\process_executor.py", line 428, in _process_worker
    r = call_item()
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\joblib\externals\loky\process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\pygmtsar\SBAS.py", line 937, in reframe
    self.make_s1a_tops(subswath, date, debug=debug)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\site-packages\pygmtsar\SBAS.py", line 1686, in make_s1a_tops
    p = subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=self.basedir)
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Arslaan\anaconda3\envs\insar\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

![Screenshot (22)](https://user-images.githubusercontent.com/110322003/200396365-47a25a4f-5785-4ff3-85d3-18b25f7e948b.png)

**Comment by mobigroup** [comment]
@Arslaan4341 Windows OS is not supported, please use MacOS or Linux systems as documented. Also, the easiest way to use PyGMTSAR on Windows system is Docker image - just install Docker Desktop software from the official site https://www.docker.com/products/docker-desktop/ and download and run the image https://hub.docker.com/r/mobigroup/pygmtsar The docker image includes Linux system with pre-installed PyGMTSAR and all the dependencies and JupyterLab interface.
