### ISSUE TITLE
[Help]:  problem in asf.dowload

### ISSUE THREAD

**Issue by jie666-6** [mobigroup/gmtsar#154]
**Describe the problem you encountered**
I would like to download S1 SLC data but I always get error in window and linux system. and here are the code I am using

asf = ASF(username, password)
SCENES = ['S1B_IW_SLC__1SDV_20200110T114920_20200110T114950_019754_02559E_5E5F']
SUBSWATH = 12
asf.download_scenes(DATADIR,SCENES,SUBSWATH)

**OS and software version**
Please specify your operating system and the version of PyGMTSAR you are using, if applicable.
- OS:
        Distributor ID: Ubuntu
        Description:    Ubuntu 22.04.3 LTS
        Release:        22.04
        Codename:       jammy
- PyGMTSAR version:
        pygmtsar 2024.7.14.post2
 
Here are the error I got in linux system:

(InSAR) root@14a05cacf3fd:/home/workdir/06_InSAR/code# python exmaples.py 
ASF Downloading Sentinel-1 SLC::   0%|                                                                                                                                                                                                 | 0/2 [00:00<?, ?it/s][Errno 2] No such file or directory: '/home/workdir/06_InSAR/data_dsc/S1B_IW_SLC__1SDV_20200110T114920_20200110T114950_019754_02559E_5E5F.SAFE/measurement/s1b-iw1-slc-vv-20200110t114920-20200110t114948-019754-02559e-004.tiff.tmp'
ASF Downloading Sentinel-1 SLC:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:16<00:00, 38.43s/it]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/pygmtsar/ASF.py", line 155, in download_scene
    assert os.path.getsize(fullname + '.tmp') == filesize, \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [Errno 2] No such file or directory: '/home/workdir/06_InSAR/data_dsc/S1B_IW_SLC__1SDV_20200110T114920_20200110T114950_019754_02559E_5E5F.SAFE/measurement/s1b-iw1-slc-vv-20200110t114920-20200110t114948-019754-02559e-004.tiff.tmp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/workdir/06_InSAR/code/exmaples.py", line 47, in <module>
    asf.download_scenes(DATADIR,SCENES,SUBSWATH)
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/pygmtsar/ASF.py", line 176, in download_scenes
    joblib.Parallel(n_jobs=n_jobs, backend=joblib_backend)(joblib.delayed(download_scene)\
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/InSAR/lib/python3.12/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
FileNotFoundError: [Errno 2] No such file or directory: '/home/workdir/06_InSAR/data_dsc/S1B_IW_SLC__1SDV_20200110T114920_20200110T114950_019754_02559E_5E5F.SAFE/measurement/s1b-iw1-slc-vv-20200110t114920-20200110t114948-019754-02559e-004.tiff.tmp'

Does anybody know what the problem is? Thanks in advance

**Comment by jie666-6** [comment]
In linux system, asf.download works.

But I am still do not find the solution for win10

**Comment by AlexeyPechnikov** [comment]
The easiest way to use PyGMTSAR on Windows is by utilizing the Docker image available at Docker Hub: https://hub.docker.com/r/pechnikov/pygmtsar. You can find detailed instructions in the PyGMTSAR introduction book available in this repository.
