### ISSUE TITLE
[Help]: Regarding parallel SBAS step

### ISSUE THREAD

**Issue by AmiraZakii** [mobigroup/gmtsar#3]
Hello,
I started to use the pygmtsar and try to test the script you provide on my machine. I was stuck in the SBAS parallel processing step due to an encoding error. should I change the SBAS.py can you help me, please?

![error1](https://user-images.githubusercontent.com/89259389/191571974-e99d9b92-42ea-4ce9-a306-8739c2c7bebe.JPG)
![error_2](https://user-images.githubusercontent.com/89259389/191571979-d5a92901-e4ea-48f4-9727-c98461aa0495.JPG)

**Comment by mobigroup** [comment]
Please show your output for this command:

sbas.df

**Comment by geodesy-iasbs** [comment]
Hi, 
I have the same problem when running on my machine, Here are my error and output for sbas.df. Apreciate your help.
`sbas.stack_parallel()`
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/pygmtsar/SBAS.py", line 1833, in stack_rep
    r_grd = self.offset2shift(r_xyz, rmax, amax)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/pygmtsar/SBAS.py", line 1576, in offset2shift
    grid = griddata((xyz[:,0], xyz[:,1]), xyz[:,2], (grid_r, grid_a), method=method)
  File "/home/geodesy/miniconda3/envs/gmtsar/lib/python3.10/site-packages/scipy/interpolate/_ndgriddata.py", line 260, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 280, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1846, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 358, in scipy.spatial._qhull._Qhull.__init__
scipy.spatial._qhull.QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0

While executing:  | qhull d Q12 Qt Qbb Qc Qz
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 389283575  delaunay  Q12-allow-wide  Qtriangulate  Qbbound-last
  Qcoplanar-keep  Qz-infinity-point  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 8.3e+03  Error-roundoff 9.6e-12  _one-merge 6.7e-11
  Visible-distance 1.9e-11  U-max-coplanar 1.9e-11  Width-outside 3.8e-11
  _wide-facet 1.1e-10  _maxoutside 7.7e-11

"""

The above exception was the direct cause of the following exception:

QhullError                                Traceback (most recent call last)
Cell In [42], line 1
----> 1 sbas.stack_parallel()

File ~/miniconda3/envs/gmtsar/lib/python3.10/site-packages/pygmtsar/SBAS.py:1902, in SBAS.stack_parallel(self, dates, n_jobs, **kwargs)
   1900 # prepare secondary images
   1901 with self.tqdm_joblib(tqdm(desc='Aligning', total=len(dates)*len(subswaths))) as progress_bar:
-> 1902     joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(self.stack_rep)(subswath, date, **kwargs) \
   1903                                    for date in dates for subswath in subswaths)

File ~/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/parallel.py:1098, in Parallel.__call__(self, iterable)
   1095     self._iterating = False
   1097 with self._backend.retrieval_context():
-> 1098     self.retrieve()
   1099 # Make sure that we get a last message telling us we are done
   1100 elapsed_time = time.time() - self._start_time

File ~/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/parallel.py:975, in Parallel.retrieve(self)
    973 try:
    974     if getattr(self._backend, 'supports_timeout', False):
--> 975         self._output.extend(job.get(timeout=self.timeout))
    976     else:
    977         self._output.extend(job.get())

File ~/miniconda3/envs/gmtsar/lib/python3.10/site-packages/joblib/_parallel_backends.py:567, in LokyBackend.wrap_future_result(future, timeout)
    564 """Wrapper for Future.result to implement the same behaviour as
    565 AsyncResults.get from multiprocessing."""
    566 try:
--> 567     return future.result(timeout=timeout)
    568 except CfTimeoutError as e:
    569     raise TimeoutError from e

File ~/miniconda3/envs/gmtsar/lib/python3.10/concurrent/futures/_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File ~/miniconda3/envs/gmtsar/lib/python3.10/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0

While executing:  | qhull d Q12 Qt Qbb Qc Qz
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 389283575  delaunay  Q12-allow-wide  Qtriangulate  Qbbound-last
  Qcoplanar-keep  Qz-infinity-point  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 8.3e+03  Error-roundoff 9.6e-12  _one-merge 6.7e-11
  Visible-distance 1.9e-11  U-max-coplanar 1.9e-11  Width-outside 3.8e-11
  _wide-facet 1.1e-10  _maxoutside 7.7e-11
  
 `sbas.df`
 

  | datetime | orbit | mission | polarization | subswath | datapath | metapath | orbitpath | geometry
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

2015-01-21 13:44:13 | D | S1A | VV | 1 | raw_orig/s1a-iw1-slc-vv-20150121t134413-20150121t134424-004270-005317-001.tiff | raw_orig/s1a-iw1-slc-vv-20150121t134413-20150121t134424-004270-005317-001.xml | raw_orig/S1A_OPER_AUX_POEORB_OPOD_20150211T122339_V20150120T225944_20150122T005944.EOF | POLYGON ((-114.64120 32.61750, -115.63261 32.77573, -115.74567 32.06737, -114.75426 31.90914, -114.64120 32.61750))
2015-03-10 13:44:12 | D | S1A | VV | 1 | raw_orig/s1a-iw1-slc-vv-20150310t134412-20150310t134424-004970-006386-001.tiff | raw_orig/s1a-iw1-slc-vv-20150310t134412-20150310t134424-004970-006386-001.xml | raw_orig/S1A_OPER_AUX_POEORB_OPOD_20150331T123006_V20150309T225944_20150311T005944.EOF | POLYGON ((-114.64089 32.61808, -115.63217 32.77630, -115.74528 32.06769, -114.75400 31.90946, -114.64089 32.61808))
2015-04-03 13:44:13 | D | S1A | VV | 1 | raw_orig/s1a-iw1-slc-vv-20150403t134413-20150403t134424-005320-006bc4-001.tiff | raw_orig/s1a-iw1-slc-vv-20150403t134413-20150403t134424-005320-006bc4-001.xml | raw_orig/S1A_OPER_AUX_POEORB_OPOD_20150424T123026_V20150402T225944_20150404T005944.EOF | POLYGON ((-114.64322 32.60958, -115.63290 32.76751, -115.74326 32.07591, -114.75358 31.91797, -114.64322 32.60958))
2015-04-27 13:44:14 | D | S1A | VV | 1 | raw_orig/s1a-iw1-slc-vv-20150427t134414-20150427t134426-005670-00745c-001.tiff | raw_orig/s1a-iw1-slc-vv-20150427t134414-20150427t134426-005670-00745c-001.xml | raw_orig/S1A_OPER_AUX_POEORB_OPOD_20150518T122528_V20150426T225944_20150428T005944.EOF | POLYGON ((-114.64307 32.60829, -115.63270 32.76624, -115.74309 32.07464, -114.75346 31.91668, -114.64307 32.60829))
2015-05-21 13:44:15 | D | S1A | VV | 1 | raw_orig/s1a-iw1-slc-vv-20150521t134415-20150521t134427-006020-007c3f-001.tiff | raw_orig/s1a-iw1-slc-vv-20150521t134415-20150521t134427-006020-007c3f-001.xml | raw_orig/S1A_OPER_AUX_POEORB_OPOD_20150611T122710_V20150520T225944_20150522T005944.EOF | POLYGON ((-114.64223 32.60828, -115.63194 32.76625, -115.74233 32.07465, -114.75262 31.91668, -114.64223 32.60828))

**Comment by mobigroup** [comment]
@geodesy-iasbs Could you share your notebook? I can’t reproduce the error without your use case.

**Comment by Meysam-Amiri** [comment]
> 
Yes, here you are. Thanks for your help
https://colab.research.google.com/drive/1P1a4zeHRjItbDI8NtTFvnysDrva0BLxy?usp=sharing

**Comment by mobigroup** [comment]
@Meysam-Amiri Do you connect your local runtime miniconda Python 3.10.4?

**Comment by Meysam-Amiri** [comment]
Yes I do.

**Comment by mobigroup** [comment]
I suppose you don't have installed GMTSAR with the binaries directory added to system PATH.

**Comment by mobigroup** [comment]
@Meysam-Amiri You'd use Docker image to run PyGMTSAR locally: https://hub.docker.com/r/mobigroup/pygmtsar

**Comment by geodesy-iasbs** [comment]
Dear @mobigroup, Thanks for the docker. It is restricted to get access right now from Iran! I will give it a try later. BTW, I have installed GMTSAR from scratch on my local machine and launched it from /usr/local and python Python 3.7.10. I am getting this new error when running `sbas.stack_parallel()`. When I ran this line the code snippets opens in the right panel for importing google.colab and instaling it ruins the jupyter notebook! I am not sure if the google.colab is related to this error. Any idea how to slove it?
Link of notebook: [https://colab.research.google.com/drive/1e15up5wdQP9nUBh6c7WxEylVYoFx79N9?usp=sharing](url)
---------------------------------------------------------------------------
QhullError                                Traceback (most recent call last)
[/tmp/ipykernel_26100/1628302268.py](https://localhost:8080/#) in <module>
----> 1 sbas.stack_parallel()

5 frames
[/usr/lib/python3.7/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0

While executing:  | qhull d Qc Qbb Q12 Qz Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 1041762093  delaunay  Qcoplanar-keep  Qbbound-last  Q12-allow-wide
  Qz-infinity-point  Qtriangulate  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 8.3e+03  Error-roundoff 9.6e-12  _one-merge 6.7e-11
  Visible-distance 1.9e-11  U-max-coplanar 1.9e-11  Width-outside 3.8e-11
  _wide-facet 1.1e-10  _maxoutside 7.7e-11

**Comment by geodesy-iasbs** [comment]
Moreover, I have tested with a python script manually and got same error. 
geodesy@geodesy-ProLiant-DL380-Gen9:/media/geodesy/Meysam/pygmtsar$ python3 test.py 
Reference: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:17<00:00, 17.97s/it]
Aligning: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.10s/it]
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    sbas.stack_parallel()
  File "/usr/local/lib/python3.7/dist-packages/pygmtsar/SBAS.py", line 1895, in stack_parallel
    for date in dates for subswath in subswaths)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
scipy.spatial.qhull.QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0

While executing:  | qhull d Qbb Qt Q12 Qz Qc
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 1048585735  delaunay  Qbbound-last  Qtriangulate  Q12-allow-wide
  Qz-infinity-point  Qcoplanar-keep  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 8.3e+03  Error-roundoff 9.6e-12  _one-merge 6.7e-11
  Visible-distance 1.9e-11  U-max-coplanar 1.9e-11  Width-outside 3.8e-11
  _wide-facet 1.1e-10  _maxoutside 7.7e-11

**Comment by mobigroup** [comment]
Try this command in your notebook:
```
!gmtsar_sharedir.csh 
```
or in your command line shell:
```
gmtsar_sharedir.csh 
```

**Comment by geodesy-iasbs** [comment]
geodesy@geodesy-ProLiant-DL380-Gen9:/media/geodesy/Meysam/pygmtsar$ gmtsar_sharedir.csh 
/usr/local/GMTSAR/share/gmtsar

**Comment by mobigroup** [comment]
Ok, it works. And try these two commands in your notebooks different cells:

```
!gmtsar_sharedir.csh
```

```
!make_gaussian_filter 
```

**Comment by geodesy-iasbs** [comment]
`!gmtsar_sharedir.csh`
/usr/local/GMTSAR/share/gmtsar
`!make_gaussian_filter` 
Usage: make_gaussian_filter name_of_PRM_file RNG_DEC AZI_DEC WAVELENGTH(m)

Example: make_gaussian_filter IMG-HH-ALPSRP211830620-H1.0__A.PRM 2 4 200

Output: gauss_200

**Comment by mobigroup** [comment]
Hmm, it looks ok. Python 3.7 on Ubuntu 18.04 (Google Colab environment) is well tested but how about your OS? Please show your output for the commands below:

uname -a

cat /etc/lsb_release

And maybe are you able to download the docker image from Apple iCloud? I could share it.

**Comment by geodesy-iasbs** [comment]
geodesy@geodesy-ProLiant-DL380-Gen9:/media/geodesy/Meysam/pygmtsar$ uname -a
Linux geodesy-ProLiant-DL380-Gen9 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
geodesy@geodesy-ProLiant-DL380-Gen9:/media/geodesy/Meysam/pygmtsar$ 
geodesy@geodesy-ProLiant-DL380-Gen9:/media/geodesy/Meysam/pygmtsar$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
It must be a problem in my installation. I would try again.

**Comment by mobigroup** [comment]
@geodesy-iasbs Ubuntu 16.04 is outdated and unsupported for about a year and so that’s strongly recommended to upgrade your system. Ubuntu 18.04 is well tested using GitHub Actions continuous integration (CI) tests and Jupyter notebooks on Google Colab. In case when upgrade is impossible you’d launch modern Ubuntu in chroot: https://wiki.ubuntu.com/DebootstrapChroot

**Comment by Arslaan4341** [comment]
> Hello, I started to use the pygmtsar and try to test the script you provide on my machine. I was stuck in the SBAS parallel processing step due to an encoding error. should I change the SBAS.py can you help me, please?
> 
> ![error1](https://user-images.githubusercontent.com/89259389/191571974-e99d9b92-42ea-4ce9-a306-8739c2c7bebe.JPG) ![error_2](https://user-images.githubusercontent.com/89259389/191571979-d5a92901-e4ea-48f4-9727-c98461aa0495.JPG)

@AmiraZakii @mobigroup Is this issue solved for pygmtsar?

**Comment by mobigroup** [comment]
@Arslaan4341 2 separate issues discussed above: GMTSAR binaries are not installed and Ubuntu 16 is not supported.
