### ISSUE TITLE
[Help]: UnicodeDecode Error while running sbas.stack_parallel() and sbas.baseline_pairs()

### ISSUE THREAD

**Issue by kinreich** [mobigroup/gmtsar#37]
When trying to run sbas.stack_parallel() and sbas.baseline_pairs() Getting error:
 "UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 0: ordinal not in range(128)" 

(Running code in pycharm console, 2023.1)

OS: Unbuntu 20.04
GMTSAR version: 6.2.2
Python version: 3.10.11
Unicode: echo $LANG output: en_US.UTF-8

**Log file** when running sbas.stack_parallel()
`Reference: 100%|██████████| 3/3 [00:10<00:00,  3.59s/it]
Aligning:  13%|█▎        | 39/291 [00:03<00:23, 10.51it/s]
Traceback (most recent call last):
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-935b05484946>", line 1, in <module>
    sbas.stack_parallel()
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_stack.py", line 235, in stack_parallel
    joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(self.stack_rep)(subswath, date, **kwargs) \
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 0: ordinal not in range(128)`

**Comment by mobigroup** [comment]
Use GMTSAR master branch from the GitHub. Google Colab noteboks install the master version and there is no the error.

**Comment by kinreich** [comment]
This solved the issue - Thank you!
