### ISSUE TITLE
[Help]: Initializing SBAS post-processing - open_grids does not recognize merged grd files

### ISSUE THREAD

**Issue by kinreich** [mobigroup/gmtsar#45]
Hello,
After running most of the processing on the data, including merging of the sub-swaths and unwrapping, python crashed (unrelated).
In order to continue processing and data analyzing, I want to run sbas.open_grids, detrending, sbas.sbas() etc, therefore need to initialize new sbas object (with force=False in order to save older data).

sbas.open_grids failing because does not find files regarding separate sub-swaths, output folder only has grd files of F123 merged subswaths.

How do I get sbas object to recognize and regard only merged subswaths files in these additional processes?

OS: Unbuntu 20.04
GMTSAR version: 6.2.2
Python version: 3.10.11

**Log file** when running unwraps_ra = sbas.open_grids(pairs, 'unwrap',add_subswath=True)
`Traceback (most recent call last):
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 210, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('/home/name/disk-one/DS_Data_2014_2023/asc/data_output/F1_20141210_20150115_unwrap.grd',), 'r', (('decode_vlen_strings', True), ('invalid_netcdf', None)), '90889ae3-3a2a-4162-a8c1-d1fdc5482508']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-e238d5766e82>", line 1, in <module>
    unwraps_ra = sbas.open_grids(pairs, 'unwrap',add_subswath=True)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_base.py", line 365, in open_grids
    da = open_grid(filename)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_base.py", line 321, in open_grid
    da = xr.open_dataarray(filename, engine=self.engine, chunks=chunksize)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/api.py", line 686, in open_dataarray
    dataset = open_dataset(
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/api.py", line 525, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 413, in open_dataset
    store = H5NetCDFStore.open(
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 176, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 127, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 187, in ds
    return self._acquire()
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 179, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 198, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 216, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/h5netcdf/core.py", line 973, in __init__
    self._h5file = self._h5py.File(
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/name/disk-one/DS_Data_2014_2023/asc/data_output/F1_20141210_20150115_unwrap.grd', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

**Comment by mobigroup** [comment]
You can use the function sbas.pairs() to look up all the available grids. By default, it looks for grids with the 'phasefilt' name.

```
sbas = SBAS(DATADIR, DEMFILE, basedir=WORKDIR, force=False)
pairs = sbas.pairs()
unwraps_ra  = sbas.open_grids(pairs, 'unwrap')
unwraps_ra 
```

If you call sbas.pairs(dates=True), it will not only return the interferogram pair list but also provide all the scene dates as well.
```
pairs, dates = sbas.pairs(dates=True)
```

And there's an even easier way using the dump() and restore() functions. With these functions, you only need to provide the WORKDIR path to restore your state. By the way, you can still use sbas.pairs() to detect the SBAS pairs that have already been processed.
```
# dump current state into WORKDIR as soon as you have the interferograms pomputed and merged
sbas.dump()
# restore the current state later from other notebook to continue
# sbas = SBAS.restore(WORKDIR)
```

**Comment by kinreich** [comment]
Thank you!

Running  pairs, dates = sbas.pairs(dates=True) this error pops up:

`Traceback (most recent call last):
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-9f9e9cb1f67c>", line 1, in <module>
    pairs, dates = sbas.pairs(dates=True)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_base.py", line 414, in pairs
    pattern = self.get_filenames(None, None, f'????????_????????_{name}')
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_base.py", line 166, in get_filenames
    subswath = self.get_subswath(subswath)
  File "/home/name/pythonProject/venv/lib/python3.10/site-packages/pygmtsar/SBAS_base.py", line 155, in get_subswath
    assert len(subswaths)==1, f'ERROR: multiple subswaths {subswaths} found, merge them first using SBAS.merge_parallel()'
AssertionError: ERROR: multiple subswaths [1 2 3] found, merge them first using SBAS.merge_parallel()`

**Comment by mobigroup** [comment]
It seems that you haven't merged the subswaths, which makes the continuation of the processing a bit tricky. I recommend trying the following code for your case:

```
sbas = SBAS(DATADIR, DEMFILE, basedir=WORKDIR, force=False)
# get all the subswaths like [1, 2, 3]
subswaths = sbas.get_subswaths()
# emulate the merging
sbas.df = sbas.df[sbas.df.subswath == subswaths[0]]
sbas.df['subswath'] = ''.join(map(str, subswaths))
# for now, we can work as expected with the merged subswaths
pairs = sbas.pairs()
unwraps_ra  = sbas.open_grids(pairs, 'unwrap')
unwraps_ra 
```
