### ISSUE TITLE
[Help]: Running into error during sbas.stack_parallel step of SBAS example 

### ISSUE THREAD

**Issue by afpoley** [mobigroup/gmtsar#66]
**Describe the problem you met**
I am trying to run the provided SBAS example [link](https://colab.research.google.com/drive/1xhVedrIvNS66jGKgS30Dgqy0S31uJ8gm?usp=sharing#scrollTo=xFqW-no-KZs9) on my local machine. I installed PYGMTSAR via [pip](https://pypi.org/project/pygmtsar/) and am able to run the download orbit and DEM functions. When I try to run stack_parallel I get this error: 

`Reference:   0%|                                                                                | 0/1 [00:14<?, ?it/s]Traceback (most recent call last):
  File "/mnt/c/Users/andrew.poley/PycharmProjects/cheatgrass/pygmtsar/sbas.py", line 61, in <module>
    sbas.stack_parallel(n_jobs=1)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pygmtsar/SBAS_stack.py", line 231, in stack_parallel
    joblib.Parallel(n_jobs=n_jobs)(joblib.delayed(self.stack_ref)(subswath, **kwargs) for subswath in subswaths)
  File "/home/afpoley/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
  File "/home/afpoley/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pygmtsar/SBAS_stack.py", line 69, in stack_ref
    .calc_dop_orb(inplace=True).update().get('earth_radius')
  File "/home/afpoley/.local/lib/python3.10/site-packages/pygmtsar/PRM.py", line 311, in get
    out = [self.df.loc[[key]].iloc[0].values[0] for key in args]
  File "/home/afpoley/.local/lib/python3.10/site-packages/pygmtsar/PRM.py", line 311, in <listcomp>
    out = [self.df.loc[[key]].iloc[0].values[0] for key in args]
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1382, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1322, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1520, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6114, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/afpoley/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6175, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['earth_radius'], dtype='object', name='name')] are in the [index]"`

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu-20.04 via wsl on windows 11

**Reproduce the problem**
I downloaded the dataset from the colab notebook and ran the code below:

**Data dir:**
![image](https://github.com/mobigroup/gmtsar/assets/35944422/3529fac5-fb13-48d9-a385-4ce930c113fb)

**code:** 

`import platform, sys, os
import xarray as xr
import numpy as np
import pandas as pd
from dask.distributed import Client
import matplotlib.pyplot as plt
import matplotlib
from pygmtsar import SBAS
import warnings # supress numpy warnings
warnings.filterwarnings('ignore')

# use default GMTSAR installation path
PATH = os.environ['PATH']
if PATH.find('GMTSAR') == -1:
    PATH = os.environ['PATH'] + ':/usr/local/GMTSAR/bin/'
    # %env PATH {PATH}

# Define parameters
MASTER = '2015-01-21'
WORKDIR = f'/mnt/d/analysis/pygmtsar/example'
DATADIR = f'/mnt/d/data/sentinel-1/well_injection/example'
DEMFILE = f'/mnt/d/data/sentinel-1/well_injection/example/dem.grd'
BASEDAYS = 100
BASEMETERS = 150
DEFOMAX = 0
POLARIZATION = 'VV'

# Run local dask cluster
if __name__ == '__main__':
    client = Client()
    client

    # Init SBAS
    sbas = SBAS(datadir=DATADIR, dem_filename=DEMFILE, basedir=WORKDIR, landmask_filename=None, filter_orbit=None, filter_mission=None,
                filter_subswath=None, filter_polarization=POLARIZATION, force=False).set_master(MASTER)
    df = sbas.to_dataframe()
    print(df)

    # Align a stack of images
    sbas.stack_parallel(n_jobs=1)

`

**Comment by AlexeyPechnikov** [comment]
It appears that you don't have GMTSAR binary tools installed, or they are not located in the expected path. Please refer to the installation commands for Ubuntu provided in the notebook cell titled 'Install GMTSAR'.

**Comment by afpoley** [comment]
I uninstalled everything and did a full reinstall. This seems to have fixed the issue! Thank you!
